# Generated by Django 4.2.3 on 2023-08-26 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_cartitem_cart_alter_cartitem_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'product', 'quantity')},
        ),
    ]
